// Comprehensive timezone data covering all major cities worldwide
const timezones = [
  // North America - USA
  {
    id: "america/new_york",
    city: "New York",
    country: "USA",
    timezone: "America/New_York",
  },
  {
    id: "america/los_angeles",
    city: "Los Angeles",
    country: "USA",
    timezone: "America/Los_Angeles",
  },
  {
    id: "america/chicago",
    city: "Chicago",
    country: "USA",
    timezone: "America/Chicago",
  },
  {
    id: "america/denver",
    city: "Denver",
    country: "USA",
    timezone: "America/Denver",
  },
  {
    id: "america/phoenix",
    city: "Phoenix",
    country: "USA",
    timezone: "America/Phoenix",
  },
  {
    id: "america/detroit",
    city: "Detroit",
    country: "USA",
    timezone: "America/Detroit",
  },
  {
    id: "america/miami",
    city: "Miami",
    country: "USA",
    timezone: "America/New_York",
  },
  {
    id: "america/boston",
    city: "Boston",
    country: "USA",
    timezone: "America/New_York",
  },
  {
    id: "america/seattle",
    city: "Seattle",
    country: "USA",
    timezone: "America/Los_Angeles",
  },
  {
    id: "america/atlanta",
    city: "Atlanta",
    country: "USA",
    timezone: "America/New_York",
  },
  {
    id: "america/dallas",
    city: "Dallas",
    country: "USA",
    timezone: "America/Chicago",
  },
  {
    id: "america/las_vegas",
    city: "Las Vegas",
    country: "USA",
    timezone: "America/Los_Angeles",
  },
  {
    id: "america/san_francisco",
    city: "San Francisco",
    country: "USA",
    timezone: "America/Los_Angeles",
  },
  {
    id: "america/washington",
    city: "Washington DC",
    country: "USA",
    timezone: "America/New_York",
  },
  {
    id: "america/philadelphia",
    city: "Philadelphia",
    country: "USA",
    timezone: "America/New_York",
  },
  {
    id: "america/houston",
    city: "Houston",
    country: "USA",
    timezone: "America/Chicago",
  },
  {
    id: "america/minneapolis",
    city: "Minneapolis",
    country: "USA",
    timezone: "America/Chicago",
  },
  {
    id: "america/portland",
    city: "Portland",
    country: "USA",
    timezone: "America/Los_Angeles",
  },
  {
    id: "america/nashville",
    city: "Nashville",
    country: "USA",
    timezone: "America/Chicago",
  },
  {
    id: "america/orlando",
    city: "Orlando",
    country: "USA",
    timezone: "America/New_York",
  },

  // North America - Canada
  {
    id: "america/toronto",
    city: "Toronto",
    country: "Canada",
    timezone: "America/Toronto",
  },
  {
    id: "america/vancouver",
    city: "Vancouver",
    country: "Canada",
    timezone: "America/Vancouver",
  },
  {
    id: "america/montreal",
    city: "Montreal",
    country: "Canada",
    timezone: "America/Montreal",
  },
  {
    id: "america/calgary",
    city: "Calgary",
    country: "Canada",
    timezone: "America/Edmonton",
  },
  {
    id: "america/ottawa",
    city: "Ottawa",
    country: "Canada",
    timezone: "America/Toronto",
  },
  {
    id: "america/winnipeg",
    city: "Winnipeg",
    country: "Canada",
    timezone: "America/Winnipeg",
  },
  {
    id: "america/halifax",
    city: "Halifax",
    country: "Canada",
    timezone: "America/Halifax",
  },

  // North America - Mexico & Central America
  {
    id: "america/mexico_city",
    city: "Mexico City",
    country: "Mexico",
    timezone: "America/Mexico_City",
  },
  {
    id: "america/guadalajara",
    city: "Guadalajara",
    country: "Mexico",
    timezone: "America/Mexico_City",
  },
  {
    id: "america/tijuana",
    city: "Tijuana",
    country: "Mexico",
    timezone: "America/Tijuana",
  },
  {
    id: "america/cancun",
    city: "Cancun",
    country: "Mexico",
    timezone: "America/Cancun",
  },
  {
    id: "america/guatemala",
    city: "Guatemala City",
    country: "Guatemala",
    timezone: "America/Guatemala",
  },
  {
    id: "america/san_jose",
    city: "San José",
    country: "Costa Rica",
    timezone: "America/Costa_Rica",
  },
  {
    id: "america/panama",
    city: "Panama City",
    country: "Panama",
    timezone: "America/Panama",
  },

  // South America
  {
    id: "america/sao_paulo",
    city: "São Paulo",
    country: "Brazil",
    timezone: "America/Sao_Paulo",
  },
  {
    id: "america/rio_de_janeiro",
    city: "Rio de Janeiro",
    country: "Brazil",
    timezone: "America/Sao_Paulo",
  },
  {
    id: "america/brasilia",
    city: "Brasília",
    country: "Brazil",
    timezone: "America/Sao_Paulo",
  },
  {
    id: "america/manaus",
    city: "Manaus",
    country: "Brazil",
    timezone: "America/Manaus",
  },
  {
    id: "america/fortaleza",
    city: "Fortaleza",
    country: "Brazil",
    timezone: "America/Fortaleza",
  },
  {
    id: "america/buenos_aires",
    city: "Buenos Aires",
    country: "Argentina",
    timezone: "America/Argentina/Buenos_Aires",
  },
  {
    id: "america/santiago",
    city: "Santiago",
    country: "Chile",
    timezone: "America/Santiago",
  },
  {
    id: "america/lima",
    city: "Lima",
    country: "Peru",
    timezone: "America/Lima",
  },
  {
    id: "america/bogota",
    city: "Bogotá",
    country: "Colombia",
    timezone: "America/Bogota",
  },
  {
    id: "america/caracas",
    city: "Caracas",
    country: "Venezuela",
    timezone: "America/Caracas",
  },
  {
    id: "america/quito",
    city: "Quito",
    country: "Ecuador",
    timezone: "America/Guayaquil",
  },
  {
    id: "america/montevideo",
    city: "Montevideo",
    country: "Uruguay",
    timezone: "America/Montevideo",
  },
  {
    id: "america/asuncion",
    city: "Asunción",
    country: "Paraguay",
    timezone: "America/Asuncion",
  },
  {
    id: "america/la_paz",
    city: "La Paz",
    country: "Bolivia",
    timezone: "America/La_Paz",
  },

  // Europe - Western
  {
    id: "europe/london",
    city: "London",
    country: "UK",
    timezone: "Europe/London",
  },
  {
    id: "europe/dublin",
    city: "Dublin",
    country: "Ireland",
    timezone: "Europe/Dublin",
  },
  {
    id: "europe/edinburgh",
    city: "Edinburgh",
    country: "UK",
    timezone: "Europe/London",
  },
  {
    id: "europe/manchester",
    city: "Manchester",
    country: "UK",
    timezone: "Europe/London",
  },
  {
    id: "europe/glasgow",
    city: "Glasgow",
    country: "UK",
    timezone: "Europe/London",
  },
  {
    id: "europe/lisbon",
    city: "Lisbon",
    country: "Portugal",
    timezone: "Europe/Lisbon",
  },
  {
    id: "europe/madrid",
    city: "Madrid",
    country: "Spain",
    timezone: "Europe/Madrid",
  },
  {
    id: "europe/barcelona",
    city: "Barcelona",
    country: "Spain",
    timezone: "Europe/Madrid",
  },
  {
    id: "europe/valencia",
    city: "Valencia",
    country: "Spain",
    timezone: "Europe/Madrid",
  },
  {
    id: "europe/seville",
    city: "Seville",
    country: "Spain",
    timezone: "Europe/Madrid",
  },

  // Europe - Central
  {
    id: "europe/paris",
    city: "Paris",
    country: "France",
    timezone: "Europe/Paris",
  },
  {
    id: "europe/marseille",
    city: "Marseille",
    country: "France",
    timezone: "Europe/Paris",
  },
  {
    id: "europe/lyon",
    city: "Lyon",
    country: "France",
    timezone: "Europe/Paris",
  },
  {
    id: "europe/nice",
    city: "Nice",
    country: "France",
    timezone: "Europe/Paris",
  },
  {
    id: "europe/berlin",
    city: "Berlin",
    country: "Germany",
    timezone: "Europe/Berlin",
  },
  {
    id: "europe/munich",
    city: "Munich",
    country: "Germany",
    timezone: "Europe/Berlin",
  },
  {
    id: "europe/hamburg",
    city: "Hamburg",
    country: "Germany",
    timezone: "Europe/Berlin",
  },
  {
    id: "europe/cologne",
    city: "Cologne",
    country: "Germany",
    timezone: "Europe/Berlin",
  },
  {
    id: "europe/frankfurt",
    city: "Frankfurt",
    country: "Germany",
    timezone: "Europe/Berlin",
  },
  {
    id: "europe/amsterdam",
    city: "Amsterdam",
    country: "Netherlands",
    timezone: "Europe/Amsterdam",
  },
  {
    id: "europe/brussels",
    city: "Brussels",
    country: "Belgium",
    timezone: "Europe/Brussels",
  },
  {
    id: "europe/zurich",
    city: "Zurich",
    country: "Switzerland",
    timezone: "Europe/Zurich",
  },
  {
    id: "europe/geneva",
    city: "Geneva",
    country: "Switzerland",
    timezone: "Europe/Zurich",
  },
  {
    id: "europe/vienna",
    city: "Vienna",
    country: "Austria",
    timezone: "Europe/Vienna",
  },
  {
    id: "europe/rome",
    city: "Rome",
    country: "Italy",
    timezone: "Europe/Rome",
  },
  {
    id: "europe/milan",
    city: "Milan",
    country: "Italy",
    timezone: "Europe/Rome",
  },
  {
    id: "europe/venice",
    city: "Venice",
    country: "Italy",
    timezone: "Europe/Rome",
  },
  {
    id: "europe/florence",
    city: "Florence",
    country: "Italy",
    timezone: "Europe/Rome",
  },
  {
    id: "europe/naples",
    city: "Naples",
    country: "Italy",
    timezone: "Europe/Rome",
  },
  {
    id: "europe/prague",
    city: "Prague",
    country: "Czech Republic",
    timezone: "Europe/Prague",
  },
  {
    id: "europe/budapest",
    city: "Budapest",
    country: "Hungary",
    timezone: "Europe/Budapest",
  },

  // Europe - Nordic
  {
    id: "europe/stockholm",
    city: "Stockholm",
    country: "Sweden",
    timezone: "Europe/Stockholm",
  },
  {
    id: "europe/oslo",
    city: "Oslo",
    country: "Norway",
    timezone: "Europe/Oslo",
  },
  {
    id: "europe/copenhagen",
    city: "Copenhagen",
    country: "Denmark",
    timezone: "Europe/Copenhagen",
  },
  {
    id: "europe/helsinki",
    city: "Helsinki",
    country: "Finland",
    timezone: "Europe/Helsinki",
  },
  {
    id: "atlantic/reykjavik",
    city: "Reykjavik",
    country: "Iceland",
    timezone: "Atlantic/Reykjavik",
  },

  // Europe - Eastern
  {
    id: "europe/warsaw",
    city: "Warsaw",
    country: "Poland",
    timezone: "Europe/Warsaw",
  },
  {
    id: "europe/krakow",
    city: "Krakow",
    country: "Poland",
    timezone: "Europe/Warsaw",
  },
  {
    id: "europe/moscow",
    city: "Moscow",
    country: "Russia",
    timezone: "Europe/Moscow",
  },
  {
    id: "europe/st_petersburg",
    city: "St. Petersburg",
    country: "Russia",
    timezone: "Europe/Moscow",
  },
  {
    id: "europe/kiev",
    city: "Kyiv",
    country: "Ukraine",
    timezone: "Europe/Kiev",
  },
  {
    id: "europe/bucharest",
    city: "Bucharest",
    country: "Romania",
    timezone: "Europe/Bucharest",
  },
  {
    id: "europe/athens",
    city: "Athens",
    country: "Greece",
    timezone: "Europe/Athens",
  },
  {
    id: "europe/istanbul",
    city: "Istanbul",
    country: "Turkey",
    timezone: "Europe/Istanbul",
  },
  {
    id: "europe/ankara",
    city: "Ankara",
    country: "Turkey",
    timezone: "Europe/Istanbul",
  },

  // Asia - East Asia
  { id: "asia/tokyo", city: "Tokyo", country: "Japan", timezone: "Asia/Tokyo" },
  { id: "asia/osaka", city: "Osaka", country: "Japan", timezone: "Asia/Tokyo" },
  { id: "asia/kyoto", city: "Kyoto", country: "Japan", timezone: "Asia/Tokyo" },
  {
    id: "asia/yokohama",
    city: "Yokohama",
    country: "Japan",
    timezone: "Asia/Tokyo",
  },
  {
    id: "asia/nagoya",
    city: "Nagoya",
    country: "Japan",
    timezone: "Asia/Tokyo",
  },
  {
    id: "asia/seoul",
    city: "Seoul",
    country: "South Korea",
    timezone: "Asia/Seoul",
  },
  {
    id: "asia/busan",
    city: "Busan",
    country: "South Korea",
    timezone: "Asia/Seoul",
  },
  {
    id: "asia/shanghai",
    city: "Shanghai",
    country: "China",
    timezone: "Asia/Shanghai",
  },
  {
    id: "asia/beijing",
    city: "Beijing",
    country: "China",
    timezone: "Asia/Shanghai",
  },
  {
    id: "asia/guangzhou",
    city: "Guangzhou",
    country: "China",
    timezone: "Asia/Shanghai",
  },
  {
    id: "asia/shenzhen",
    city: "Shenzhen",
    country: "China",
    timezone: "Asia/Shanghai",
  },
  {
    id: "asia/chengdu",
    city: "Chengdu",
    country: "China",
    timezone: "Asia/Shanghai",
  },
  {
    id: "asia/hangzhou",
    city: "Hangzhou",
    country: "China",
    timezone: "Asia/Shanghai",
  },
  {
    id: "asia/xi_an",
    city: "Xi'an",
    country: "China",
    timezone: "Asia/Shanghai",
  },
  {
    id: "asia/hong_kong",
    city: "Hong Kong",
    country: "Hong Kong",
    timezone: "Asia/Hong_Kong",
  },
  { id: "asia/macau", city: "Macau", country: "Macau", timezone: "Asia/Macau" },
  {
    id: "asia/taipei",
    city: "Taipei",
    country: "Taiwan",
    timezone: "Asia/Taipei",
  },

  // Asia - Southeast Asia
  {
    id: "asia/singapore",
    city: "Singapore",
    country: "Singapore",
    timezone: "Asia/Singapore",
  },
  {
    id: "asia/kuala_lumpur",
    city: "Kuala Lumpur",
    country: "Malaysia",
    timezone: "Asia/Kuala_Lumpur",
  },
  {
    id: "asia/bangkok",
    city: "Bangkok",
    country: "Thailand",
    timezone: "Asia/Bangkok",
  },
  {
    id: "asia/ho_chi_minh",
    city: "Ho Chi Minh City",
    country: "Vietnam",
    timezone: "Asia/Ho_Chi_Minh",
  },
  {
    id: "asia/hanoi",
    city: "Hanoi",
    country: "Vietnam",
    timezone: "Asia/Ho_Chi_Minh",
  },
  {
    id: "asia/jakarta",
    city: "Jakarta",
    country: "Indonesia",
    timezone: "Asia/Jakarta",
  },
  {
    id: "asia/bali",
    city: "Bali",
    country: "Indonesia",
    timezone: "Asia/Makassar",
  },
  {
    id: "asia/manila",
    city: "Manila",
    country: "Philippines",
    timezone: "Asia/Manila",
  },
  {
    id: "asia/cebu",
    city: "Cebu",
    country: "Philippines",
    timezone: "Asia/Manila",
  },
  {
    id: "asia/phnom_penh",
    city: "Phnom Penh",
    country: "Cambodia",
    timezone: "Asia/Phnom_Penh",
  },
  {
    id: "asia/vientiane",
    city: "Vientiane",
    country: "Laos",
    timezone: "Asia/Vientiane",
  },
  {
    id: "asia/yangon",
    city: "Yangon",
    country: "Myanmar",
    timezone: "Asia/Yangon",
  },

  // Asia - South Asia
  {
    id: "asia/kolkata",
    city: "Mumbai",
    country: "India",
    timezone: "Asia/Kolkata",
  },
  {
    id: "asia/delhi",
    city: "New Delhi",
    country: "India",
    timezone: "Asia/Kolkata",
  },
  {
    id: "asia/bengaluru",
    city: "Bengaluru",
    country: "India",
    timezone: "Asia/Kolkata",
  },
  {
    id: "asia/chennai",
    city: "Chennai",
    country: "India",
    timezone: "Asia/Kolkata",
  },
  {
    id: "asia/hyderabad",
    city: "Hyderabad",
    country: "India",
    timezone: "Asia/Kolkata",
  },
  { id: "asia/pune", city: "Pune", country: "India", timezone: "Asia/Kolkata" },
  {
    id: "asia/ahmedabad",
    city: "Ahmedabad",
    country: "India",
    timezone: "Asia/Kolkata",
  },
  {
    id: "asia/kochi",
    city: "Kochi",
    country: "India",
    timezone: "Asia/Kolkata",
  },
  { id: "asia/goa", city: "Goa", country: "India", timezone: "Asia/Kolkata" },
  {
    id: "asia/karachi",
    city: "Karachi",
    country: "Pakistan",
    timezone: "Asia/Karachi",
  },
  {
    id: "asia/lahore",
    city: "Lahore",
    country: "Pakistan",
    timezone: "Asia/Karachi",
  },
  {
    id: "asia/islamabad",
    city: "Islamabad",
    country: "Pakistan",
    timezone: "Asia/Karachi",
  },
  {
    id: "asia/dhaka",
    city: "Dhaka",
    country: "Bangladesh",
    timezone: "Asia/Dhaka",
  },
  {
    id: "asia/colombo",
    city: "Colombo",
    country: "Sri Lanka",
    timezone: "Asia/Colombo",
  },
  {
    id: "asia/kathmandu",
    city: "Kathmandu",
    country: "Nepal",
    timezone: "Asia/Kathmandu",
  },

  // Asia - Central & West Asia
  { id: "asia/dubai", city: "Dubai", country: "UAE", timezone: "Asia/Dubai" },
  {
    id: "asia/abu_dhabi",
    city: "Abu Dhabi",
    country: "UAE",
    timezone: "Asia/Dubai",
  },
  { id: "asia/doha", city: "Doha", country: "Qatar", timezone: "Asia/Qatar" },
  {
    id: "asia/kuwait",
    city: "Kuwait City",
    country: "Kuwait",
    timezone: "Asia/Kuwait",
  },
  {
    id: "asia/riyadh",
    city: "Riyadh",
    country: "Saudi Arabia",
    timezone: "Asia/Riyadh",
  },
  {
    id: "asia/jeddah",
    city: "Jeddah",
    country: "Saudi Arabia",
    timezone: "Asia/Riyadh",
  },
  {
    id: "asia/muscat",
    city: "Muscat",
    country: "Oman",
    timezone: "Asia/Muscat",
  },
  {
    id: "asia/bahrain",
    city: "Manama",
    country: "Bahrain",
    timezone: "Asia/Bahrain",
  },
  {
    id: "asia/tehran",
    city: "Tehran",
    country: "Iran",
    timezone: "Asia/Tehran",
  },
  {
    id: "asia/baghdad",
    city: "Baghdad",
    country: "Iraq",
    timezone: "Asia/Baghdad",
  },
  {
    id: "asia/damascus",
    city: "Damascus",
    country: "Syria",
    timezone: "Asia/Damascus",
  },
  {
    id: "asia/beirut",
    city: "Beirut",
    country: "Lebanon",
    timezone: "Asia/Beirut",
  },
  {
    id: "asia/amman",
    city: "Amman",
    country: "Jordan",
    timezone: "Asia/Amman",
  },
  {
    id: "asia/jerusalem",
    city: "Jerusalem",
    country: "Israel",
    timezone: "Asia/Jerusalem",
  },
  {
    id: "asia/tel_aviv",
    city: "Tel Aviv",
    country: "Israel",
    timezone: "Asia/Jerusalem",
  },
  {
    id: "asia/tashkent",
    city: "Tashkent",
    country: "Uzbekistan",
    timezone: "Asia/Tashkent",
  },
  {
    id: "asia/almaty",
    city: "Almaty",
    country: "Kazakhstan",
    timezone: "Asia/Almaty",
  },
  {
    id: "asia/baku",
    city: "Baku",
    country: "Azerbaijan",
    timezone: "Asia/Baku",
  },
  {
    id: "asia/yerevan",
    city: "Yerevan",
    country: "Armenia",
    timezone: "Asia/Yerevan",
  },
  {
    id: "asia/tbilisi",
    city: "Tbilisi",
    country: "Georgia",
    timezone: "Asia/Tbilisi",
  },

  // Africa - North Africa
  {
    id: "africa/cairo",
    city: "Cairo",
    country: "Egypt",
    timezone: "Africa/Cairo",
  },
  {
    id: "africa/alexandria",
    city: "Alexandria",
    country: "Egypt",
    timezone: "Africa/Cairo",
  },
  {
    id: "africa/casablanca",
    city: "Casablanca",
    country: "Morocco",
    timezone: "Africa/Casablanca",
  },
  {
    id: "africa/rabat",
    city: "Rabat",
    country: "Morocco",
    timezone: "Africa/Casablanca",
  },
  {
    id: "africa/marrakech",
    city: "Marrakech",
    country: "Morocco",
    timezone: "Africa/Casablanca",
  },
  {
    id: "africa/tunis",
    city: "Tunis",
    country: "Tunisia",
    timezone: "Africa/Tunis",
  },
  {
    id: "africa/algiers",
    city: "Algiers",
    country: "Algeria",
    timezone: "Africa/Algiers",
  },
  {
    id: "africa/tripoli",
    city: "Tripoli",
    country: "Libya",
    timezone: "Africa/Tripoli",
  },

  // Africa - Sub-Saharan Africa
  {
    id: "africa/johannesburg",
    city: "Johannesburg",
    country: "South Africa",
    timezone: "Africa/Johannesburg",
  },
  {
    id: "africa/cape_town",
    city: "Cape Town",
    country: "South Africa",
    timezone: "Africa/Johannesburg",
  },
  {
    id: "africa/durban",
    city: "Durban",
    country: "South Africa",
    timezone: "Africa/Johannesburg",
  },
  {
    id: "africa/nairobi",
    city: "Nairobi",
    country: "Kenya",
    timezone: "Africa/Nairobi",
  },
  {
    id: "africa/kampala",
    city: "Kampala",
    country: "Uganda",
    timezone: "Africa/Kampala",
  },
  {
    id: "africa/dar_es_salaam",
    city: "Dar es Salaam",
    country: "Tanzania",
    timezone: "Africa/Dar_es_Salaam",
  },
  {
    id: "africa/addis_ababa",
    city: "Addis Ababa",
    country: "Ethiopia",
    timezone: "Africa/Addis_Ababa",
  },
  {
    id: "africa/kigali",
    city: "Kigali",
    country: "Rwanda",
    timezone: "Africa/Kigali",
  },
  {
    id: "africa/lagos",
    city: "Lagos",
    country: "Nigeria",
    timezone: "Africa/Lagos",
  },
  {
    id: "africa/abuja",
    city: "Abuja",
    country: "Nigeria",
    timezone: "Africa/Lagos",
  },
  {
    id: "africa/accra",
    city: "Accra",
    country: "Ghana",
    timezone: "Africa/Accra",
  },
  {
    id: "africa/dakar",
    city: "Dakar",
    country: "Senegal",
    timezone: "Africa/Dakar",
  },
  {
    id: "africa/kinshasa",
    city: "Kinshasa",
    country: "DR Congo",
    timezone: "Africa/Kinshasa",
  },
  {
    id: "africa/luanda",
    city: "Luanda",
    country: "Angola",
    timezone: "Africa/Luanda",
  },
  {
    id: "africa/maputo",
    city: "Maputo",
    country: "Mozambique",
    timezone: "Africa/Maputo",
  },
  {
    id: "africa/harare",
    city: "Harare",
    country: "Zimbabwe",
    timezone: "Africa/Harare",
  },
  {
    id: "africa/lusaka",
    city: "Lusaka",
    country: "Zambia",
    timezone: "Africa/Lusaka",
  },

  // Australia & Oceania
  {
    id: "australia/sydney",
    city: "Sydney",
    country: "Australia",
    timezone: "Australia/Sydney",
  },
  {
    id: "australia/melbourne",
    city: "Melbourne",
    country: "Australia",
    timezone: "Australia/Melbourne",
  },
  {
    id: "australia/brisbane",
    city: "Brisbane",
    country: "Australia",
    timezone: "Australia/Brisbane",
  },
  {
    id: "australia/perth",
    city: "Perth",
    country: "Australia",
    timezone: "Australia/Perth",
  },
  {
    id: "australia/adelaide",
    city: "Adelaide",
    country: "Australia",
    timezone: "Australia/Adelaide",
  },
  {
    id: "australia/darwin",
    city: "Darwin",
    country: "Australia",
    timezone: "Australia/Darwin",
  },
  {
    id: "australia/hobart",
    city: "Hobart",
    country: "Australia",
    timezone: "Australia/Hobart",
  },
  {
    id: "australia/canberra",
    city: "Canberra",
    country: "Australia",
    timezone: "Australia/Sydney",
  },
  {
    id: "pacific/auckland",
    city: "Auckland",
    country: "New Zealand",
    timezone: "Pacific/Auckland",
  },
  {
    id: "pacific/wellington",
    city: "Wellington",
    country: "New Zealand",
    timezone: "Pacific/Auckland",
  },
  {
    id: "pacific/christchurch",
    city: "Christchurch",
    country: "New Zealand",
    timezone: "Pacific/Auckland",
  },
  {
    id: "pacific/fiji",
    city: "Suva",
    country: "Fiji",
    timezone: "Pacific/Fiji",
  },
  {
    id: "pacific/honolulu",
    city: "Honolulu",
    country: "USA (Hawaii)",
    timezone: "Pacific/Honolulu",
  },
  {
    id: "pacific/tahiti",
    city: "Papeete",
    country: "French Polynesia",
    timezone: "Pacific/Tahiti",
  },
  {
    id: "pacific/samoa",
    city: "Apia",
    country: "Samoa",
    timezone: "Pacific/Apia",
  },
  {
    id: "pacific/tonga",
    city: "Nuku'alofa",
    country: "Tonga",
    timezone: "Pacific/Tongatapu",
  },
  {
    id: "pacific/port_moresby",
    city: "Port Moresby",
    country: "Papua New Guinea",
    timezone: "Pacific/Port_Moresby",
  },
  {
    id: "pacific/noumea",
    city: "Nouméa",
    country: "New Caledonia",
    timezone: "Pacific/Noumea",
  },

  // Caribbean & Atlantic
  {
    id: "america/havana",
    city: "Havana",
    country: "Cuba",
    timezone: "America/Havana",
  },
  {
    id: "america/jamaica",
    city: "Kingston",
    country: "Jamaica",
    timezone: "America/Jamaica",
  },
  {
    id: "america/santo_domingo",
    city: "Santo Domingo",
    country: "Dominican Republic",
    timezone: "America/Santo_Domingo",
  },
  {
    id: "america/puerto_rico",
    city: "San Juan",
    country: "Puerto Rico",
    timezone: "America/Puerto_Rico",
  },
  {
    id: "america/barbados",
    city: "Bridgetown",
    country: "Barbados",
    timezone: "America/Barbados",
  },
  {
    id: "america/port_of_spain",
    city: "Port of Spain",
    country: "Trinidad and Tobago",
    timezone: "America/Port_of_Spain",
  },
  {
    id: "atlantic/bermuda",
    city: "Hamilton",
    country: "Bermuda",
    timezone: "Atlantic/Bermuda",
  },
  {
    id: "atlantic/azores",
    city: "Ponta Delgada",
    country: "Portugal (Azores)",
    timezone: "Atlantic/Azores",
  },
  {
    id: "atlantic/canary",
    city: "Las Palmas",
    country: "Spain (Canary Islands)",
    timezone: "Atlantic/Canary",
  },
  {
    id: "atlantic/cape_verde",
    city: "Praia",
    country: "Cape Verde",
    timezone: "Atlantic/Cape_Verde",
  },

  // Arctic & Special Regions
  {
    id: "america/anchorage",
    city: "Anchorage",
    country: "USA (Alaska)",
    timezone: "America/Anchorage",
  },
  {
    id: "america/juneau",
    city: "Juneau",
    country: "USA (Alaska)",
    timezone: "America/Juneau",
  },
  {
    id: "america/nome",
    city: "Nome",
    country: "USA (Alaska)",
    timezone: "America/Nome",
  },
  {
    id: "america/adak",
    city: "Adak",
    country: "USA (Aleutian Islands)",
    timezone: "America/Adak",
  },
  {
    id: "asia/magadan",
    city: "Magadan",
    country: "Russia",
    timezone: "Asia/Magadan",
  },
  {
    id: "asia/vladivostok",
    city: "Vladivostok",
    country: "Russia",
    timezone: "Asia/Vladivostok",
  },
  {
    id: "asia/yakutsk",
    city: "Yakutsk",
    country: "Russia",
    timezone: "Asia/Yakutsk",
  },
  {
    id: "asia/irkutsk",
    city: "Irkutsk",
    country: "Russia",
    timezone: "Asia/Irkutsk",
  },
  {
    id: "asia/novosibirsk",
    city: "Novosibirsk",
    country: "Russia",
    timezone: "Asia/Novosibirsk",
  },
  {
    id: "asia/yekaterinburg",
    city: "Yekaterinburg",
    country: "Russia",
    timezone: "Asia/Yekaterinburg",
  },
  {
    id: "antarctica/mcmurdo",
    city: "McMurdo Station",
    country: "Antarctica",
    timezone: "Antarctica/McMurdo",
  },
];
